services:
    ds.ssolinkedin.event.listener.user_email_change:
        class: Ds\Bundle\SSOLinkedinBundle\Event\Listener\UserEmailChangeListener
        tags:
            - { name: doctrine.event_listener, event: preUpdate }
